Closes #20
viduxka/camhub pull request #25
Opened 2020-11-17 12:12 UTC by psiklos

2020-11-17 12:39 UTC, pgolity submitted a review, later dismissed
OK

2020-11-17 14:07 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/CamHubApplicationTest.java
>  }
Ennek itt nincs sok értelme, legyen `@Disabled` test inkább.

2020-11-17 14:08 UTC, gbene-vidux requested changes
Test osztályt tiltsuk le, ha nincs benne test.

2020-11-17 14:14 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/CamHubApplicationTest.java
>  }
Done

2020-11-18 06:56 UTC, pbalogh-vidux approved these changes

2020-11-18 07:26 UTC, gbene-vidux approved these changes

2020-11-18 07:27 UTC, pgolity approved these changes

2020-11-18 07:27 UTC, merged