Camera list page #27
viduxka/camhub pull request #32
Opened 2020-11-24 14:20 UTC by pbalogh-vidux

Get camera list with ajax request from "api/v1/cameras" and creating layout for the camera list items

2020-11-24 14:23 UTC, gbene-vidux commented
https://github.com/viduxka/testingo/pull/32#issuecomment-733004358

Ezt már jeleztem, hogy erre figyeljetek! Kérlek legalább a pull requestbe írd bele!

2020-11-24 14:30 UTC, gbene-vidux requested changes
PR description nem tartalmaz ChangeLogg vezérlő tag-t.

2020-11-24 14:52 UTC, gbene-vidux submitted a review, later dismissed

2020-11-24 15:20 UTC, gbene-vidux commented
hiányzik a cross-confirmation test-hez a leírás, illetve a wiremock infók!

2020-11-25 07:40 UTC, aszabo-vidux approved these changes

2020-11-25 07:41 UTC, gbene-vidux approved these changes

2020-11-25 07:43 UTC, merged