Fat jar
viduxka/camhub pull request #35
Opened 2020-12-01 12:55 UTC by pgolity

- fixed: Gradle build and bootRun

2020-12-01 12:59 UTC, gbene-vidux approved these changes, later dismissed

2020-12-01 13:54 UTC, psiklos requested changes

2020-12-01 13:54 UTC, psiklos commented on backend/build.gradle
> +bootRun.dependsOn(delFrontEnd)
újsor a végére

2020-12-01 13:59 UTC, pgolity commented on backend/build.gradle
> +bootRun.dependsOn(delFrontEnd)
Done

2020-12-01 14:02 UTC, psiklos approved these changes

2020-12-02 08:17 UTC, gbene-vidux approved these changes

2020-12-02 08:17 UTC, merged