Implementing tests
viduxka/camhub pull request #36
Opened 2020-12-04 09:37 UTC by pbalogh-vidux

Implementing unit tests. 
Run by: npm test

2020-12-04 10:47 UTC, gbene-vidux requested changes
Nem jó a PR, nincs benne changelog vezérlő tag!

https://github.com/viduxka/testingo/pull/36#issuecomment-738680142

2020-12-07 08:26 UTC, aszabo-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +    name: "Teszt camera",
Angol magyart ne keverjuk szerintem a kodban. (teszt legyen mindenhol test)

2020-12-07 08:26 UTC, aszabo-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +  const inTestCapName = Object.values(testProps)[Object.keys(testProps).length-1];
"A Teszt capability" stringet akarod megkapni? 

akkor az: testProps.capabilities

2020-12-07 08:26 UTC, aszabo-vidux commented on frontend/src/components/CapabilityTable/CapabilityTable.unit.test.js
> +  const tesztLabels =["Teszt1", "Teszt2"];
angol magyar

2020-12-07 08:26 UTC, aszabo-vidux commented on frontend/src/containers/CamListContainer/CamListContainer.js
> +    .then((json) => {
valami request error kezelés legyen.
.catch((err)  => {} )

2020-12-07 10:59 UTC, pbalogh-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +    name: "Teszt camera",
javítva

2020-12-07 11:00 UTC, pbalogh-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +  const inTestCapName = Object.values(testProps)[Object.keys(testProps).length-1];
javítottam: eredetileg egy string tömböt adtam át a testProps.capabilites-ben, ezt írtam vissza

2020-12-07 11:00 UTC, pbalogh-vidux commented on frontend/src/components/CapabilityTable/CapabilityTable.unit.test.js
> +  const tesztLabels =["Teszt1", "Teszt2"];
javítva

2020-12-07 11:00 UTC, pbalogh-vidux commented on frontend/src/containers/CamListContainer/CamListContainer.js
> +    .then((json) => {
done, alertetet dobok most ideiglenesen.

2020-12-07 11:17 UTC, aszabo-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +  const inTestCapName = Object.values(testProps)[Object.keys(testProps).length-1];
Akkor is ugyanaz  szerintem :)
Most meg ezt várod vissza ["Test capability1", "Test capability2"]
ez ugyanaz :  testProps.capabilities

2020-12-07 12:00 UTC, gbene-vidux approved these changes, later dismissed

2020-12-07 14:56 UTC, pbalogh-vidux commented on frontend/src/components/CamListItem/CamListItem.unit.test.js
> +  const inTestCapName = Object.values(testProps)[Object.keys(testProps).length-1];
igaz,done

2020-12-07 14:59 UTC, aszabo-vidux approved these changes, later dismissed

2020-12-07 15:11 UTC, gbene-vidux submitted a review, later dismissed

2020-12-07 15:12 UTC, gbene-vidux commented
Patrik, kérlek próbáld ki, hogy gradlew test-el lefutnak-e nálad a frontend tesztek, ha igen, akkor mehet a merge!

2020-12-08 08:40 UTC, gbene-vidux approved these changes

2020-12-08 08:46 UTC, aszabo-vidux approved these changes

2020-12-08 09:32 UTC, merged