M2 code cleanup
viduxka/camhub pull request #61
Opened 2021-01-11 08:42 UTC by psiklos

- added: Sonar fixes
 - added: Tests for camera scan and raw camera data factory

2021-01-11 12:23 UTC, pgolity submitted a review, later dismissed

2021-01-11 14:24 UTC, gbene-vidux requested changes

2021-01-11 14:24 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/CameraDiscoveryServiceTest.java
> +        "No DiscoveryException thrown when a discovery service is already running");
Ez így megtévesztő volt nekem, kellett egy kis idő mire rájöttem miért így csinálod. Ugye nincs beinjektálva az atomic boolean ezért nem éred el kivülről, ezért van az 'assert does not throw' rész. Itt egy tesztben két eset van tesztelve. [Ez nem feltétlen szerencsés.](https://softwareengineering.stackexchange.com/questions/266776/java-unit-testing-multiple-test-cases-in-one-test) Így a teszt neve ami látszani fog, hogy nem sikertült az nem feltétlen az lesz, ami nem sikerült.

2021-01-11 14:24 UTC, gbene-vidux commented on backend/src/main/java/net/vidux/camhub/discovery/RawCameraEvent.java
> +  private final transient RawCameraData rawCameraData;
Mi az oka, hogy ez a mező _transient_?

2021-01-11 15:07 UTC, psiklos commented on backend/src/main/java/net/vidux/camhub/discovery/RawCameraEvent.java
> +  private final transient RawCameraData rawCameraData;
https://rules.sonarsource.com/java/RSPEC-1948

Úgy gondoltam, hogy nagyon ritkán fog serializálódni ez az osztály, ezért inkább csak transient -re tettem.

2021-01-11 15:38 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/CameraDiscoveryServiceTest.java
> +        "No DiscoveryException thrown when a discovery service is already running");
Az atomic boolean -t nem lehetett beinjektálni, nem működött.
A mockFuture visszaadásával érem el azt, hogy a boolean nem fog false -ra állni. A setup része, hogy hívok egy cameraDiscoveryService.requestDiscovery() -t. Mivel ez dob egy checked exceptiont, azt vhogy le kellett kezeljem, ez vsz jobb mint egy üres try/catch.

2021-01-11 16:03 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/CameraDiscoveryServiceTest.java
> +        "No DiscoveryException thrown when a discovery service is already running");
Ennél jobb megoldás, ha készítesz egy olyan konstruktort, hogy lehetőséged legyen beinjektálni mégis a kérdéses objektumot. Ezt nem kell használnia a spring-nek, elég ha csak a mockito eléri.

2021-01-12 10:22 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/CameraDiscoveryServiceTest.java
> +        "No DiscoveryException thrown when a discovery service is already running");
Rosszul fogalmaztam, nem az injektálással volt a probléma, hanem a mockolással. Egy olyan megoldást el tudok még erre képzelni, hogy becsomagolom egy wrapper osztályba, és azt mockolom ki.

2021-01-12 10:45 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/CameraDiscoveryServiceTest.java
> +        "No DiscoveryException thrown when a discovery service is already running");
Szerintem nem kell kimockolni. Elég csak injektálni. Hint: https://stackoverflow.com/questions/20270391/mockito-inject-real-objects-into-private-autowired-fields

2021-01-13 09:38 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/RawCameraEventListenerTest.java
> +    publisher.publishRawCameraEvent(rawCameraData);
Ez itt nem csinál semmit és kihagyható

2021-01-13 09:38 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/RawCameraEventListenerTest.java
> +    verify(listener, times(1)).handleRawCameraEvent(rawCameraEvent);
Ez így mindig igaz lesz.

Ne mockold a listener -t, hanem csak spy -old, és mockold a rawCameraService -t. Azt tudod akkor verify -olni, hogy ha ha ráhívsz a handleRawCameraEvent -re, akkor a megfelelő paraméterekkel hív -e tovább a processRawCameraData -ba.

2021-01-13 09:38 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/CameraScanTest.java
> +  void testFailedWrapper2() throws IOException, TimeoutException {
testFailedWrapperTimeOut

2021-01-13 09:38 UTC, psiklos commented on backend/src/test/java/net/vidux/camhub/discovery/CameraScanTest.java
> +  void testFailedWrapper1() throws IOException, TimeoutException {
testFailedWrapperIO

2021-01-13 10:04 UTC, gbene-vidux requested changes

2021-01-13 10:04 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/CameraScanTest.java
> +        "Future did not fail with TimeOutException.");
Assertáljuk azt is, hogy a dobott exceptiön van benne a future-ben.

2021-01-14 11:35 UTC, pgolity submitted a review, later dismissed
Gradle works fine

2021-01-18 12:37 UTC, pgolity approved these changes, later dismissed
Gradle is still fine

2021-01-18 13:08 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/StreamGobblerTest.java
> +    String initialString = firstLine + newLine + "" + newLine + secondLine;
Ajánlom a StringJoiner oszutályt az ilyen feladatokra!

2021-01-18 13:10 UTC, gbene-vidux commented on backend/src/test/java/net/vidux/camhub/discovery/StreamGobblerTest.java
> +  }
Ez nem ellenőrzi, hogy van-e más is az eredmény objektumban.

2021-01-18 13:22 UTC, gbene-vidux requested changes
Legyen egy olyan eset is, hogy üres a stream!

2021-01-18 14:44 UTC, pgolity submitted a review, later dismissed

2021-01-19 13:24 UTC, gbene-vidux approved these changes

2021-01-19 13:24 UTC, merged